---
title: "Colin Fay's 10 data visualizations from dataset"
author: "Shamindra Shrotriya"
date: "7/8/2018"
output: html_document
---

## Economist Learning example

This is a code along to this amazing [10 data visualizations by Colin Fay](https://colinfay.me/1-dataset-10-dataviz-with-r/).

### Setup

```{r setup, cache=TRUE, results='hide',warning=FALSE,message=FALSE}
# pckgs <- c("tidyverse", "WDI", "gganimate")
# install.packages(pckgs)
# devtools::install_github("hrbrmstr/hrbrthemes")
# install.packages('extrafont')
library(extrafont)
# extrafont::font_import()
extrafont::loadfonts()
library(hrbrthemes)
library(tidyverse)
library(glue)
library(magrittr)
```

### Data Cleaning

We need to read in the data and rename all of the columns from French to
English. We use Google Translate to do this effectively.

```{r data_clean01, cache=TRUE, message=FALSE}
prim <- read_csv2("https://data.enseignementsup-recherche.gouv.fr/explore/dataset/fr-esr-pes-pedr-beneficiaires/download/?format=csv&amp;timezone=Europe/Berlin&amp;use_labels_for_header=true")
new_colnames <- c("year", "code_sex", "sex", "code_sector_cnu",
                  "disciplinary_sector", "code_group_corps", "body_group",
                  "code_uai", "establishment", "code_academy",
                  "academy", "code_region", "region", "code_pres", "pres",
                  "code_idex", "idex", "beneficiaries", "geo_localisation")
prim <- prim %>% 
            magrittr::set_colnames(x = ., value = new_colnames)
# head(prim) %>% View()
```

### Plot 1 - Frequency Distribution by Year

```{r plot01, cache=TRUE, message=FALSE}
prim %>%
    dplyr::group_by(year) %>% 
    dplyr::summarize(total = sum(beneficiaries)) %>% 
    ggplot2::ggplot(data = ., aes(x = year, y = total)) +
    ggplot2::geom_bar(stat = "identity") +
    labs(x="Year",
       title="Number of Awards per year",
       subtitle="This is the first plot",
       caption="Based on Colin Fay's blogpost") +
    hrbrthemes::theme_ipsum()
```

### Plot 2 - Frequency Distribution by Year and Discipline

```{r plot02, cache=TRUE, message=FALSE}
prim %>%
    dplyr::group_by(year, disciplinary_sector) %>% 
    dplyr::summarize(total = sum(beneficiaries)) %>% 
    ggplot2::ggplot(data = ., aes(x = year, y = total, 
                                  fill = disciplinary_sector)) +
    ggplot2::geom_bar(stat = "identity", position = "fill") +
    labs(x="Year",
       title="Number of Awards per year and discipline",
       subtitle="This is the second plot",
       caption="Based on Colin Fay's blogpost") +
    hrbrthemes::theme_ipsum()
```

### Plot 3 - Value by sector

```{r plot03, cache=TRUE, message=FALSE}
prim %>%
    dplyr::group_by(year, beneficiaries, disciplinary_sector, ) %>% 
    dplyr::summarize(total = sum(beneficiaries)) %>% 
    ggplot2::ggplot(data = ., aes(x = year, y = total, 
                                  group = disciplinary_sector)) +
    ggplot2::geom_bar(stat = "identity", position = "fill") +
    labs(x="Year",
       title="Number of Awards per year and discipline",
       subtitle="This is the second plot",
       caption="Based on Colin Fay's blogpost") +
    hrbrthemes::theme_ipsum()
```
